sdf_func: 'torus'
sdf_params: [0.1, 0.025]
num_particles: 1000
rot_x: 45
rot_y: 90
rot_z: 45
pos_x: 0
pos_y: 0.2
pos_z: 0
points_file: '/data18/hmittal/visual-diff-sim/pac_nerf/simulation_data/torus/0.ply'
