grogu: False
lr: 0.1
save_dir: None
local_dir: None
material_data: oracle_Data/elastic_torus_orig
mu_init_val: 3.
Fdet_reg: False
focal_loss: False
grad_clip_val: False
grad_clip_norm: False
weight_decay: False
nn_activation: 'elu'
nn_init_weight: 'uniform_5'
stress_loss: False
Ftransform: 'F'
Ftmptransform: 'F'
batch_size: 160
load_model:
lambda_lr_rate: 0.02
hidden_size: 128
cuda_chunk_size: 4096
particles_ti_root: 1024
T_0: 100
T_mult: 1
cosine_cycles: 2000
epochs: 2000000
shuffle: True
step_lr_step_size: 30
resume: False
embed_dim: 128
traj_latent_path: None
gt_X_file: None
discount_factor: 0.9
fproj_load_model:
azs: False
traj_load_idx: -1
material_type_dir: None
latent_init_config: None
traj_latent_idx: None
config_path: None
eval_gt_nn_scenario: None