cuda_chunk_size: 2900
particles_ti_root: 500
save_dir: None
local_dir: None
dataset_dir: None
camera_json_path: None
image_dir: None
nn_activation: gelu
hidden_size: 4096
embed_dim: 1024
load_model: None
traj_latent_path: None
batch_size: 32
lr: 1e-4
step_lr_step_size: 10000
epochs: 2
gt_X_file: None
fproj_load_model: None
latent_init_config: None
material_type_dir: None
object_scale_factor: 0.25
psc: False
wandb_name: particle_pos_loss
latent_idx: None
traj_latent_idx: None
hou_vis: False
traj_data_dir: None