cuda_chunk_size: 2900
particles_ti_root: 500
grogu: False
save_dir: None
local_dir: None
gaussian_path: /home/hmittal/diff-sim/visual-diff-sim/gaussian-splatting/output/d8d96670-0/point_cloud/iteration_30000/point_cloud.ply
internal_points_path: /data18/hmittal/visual-diff-sim/pac_nerf/simulation_data/torus/0.ply
num_simulate_gaussians: 1048
num_internal_particles: 1000
#gaussian_path: /home/hmittal/diff-sim/visual-diff-sim/gaussian-splatting/output/2a8b0c9c-a/point_cloud/iteration_30000/point_cloud.ply
dataset_dir: /data18/hmittal/visual-diff-sim/PhysDreamer_PACNeRF/torus
camera_json_path: /data18/hmittal/visual-diff-sim/pac_nerf/data/torus/all_data.json
image_dir: /data18/hmittal/PAC-NeRF/data/torus/data
simulate_gaussians_internal: True
nn_activation: gelu
hidden_size: 4096
embed_dim: 1024
load_model: None
traj_latent_path: None
batch_size: 32
lr: 1e-4
step_lr_step_size: 10000
epochs: 2
gt_X_file: None
fproj_load_model: None
latent_init_config: None
material_type_dir: None
object_scale_factor: 0.25
psc: False
wandb_name: particle_pos_loss
latent_idx: None
traj_latent_idx: None
hou_vis: False
traj_data_dir: None